spring:
    profiles: local
eureka:
    client:
      registerWithEureka: false
      fetchRegistry: false
      server:
          waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
           defaultZone: ${EUREKA_URI:https://payee-dicovery-server-po7pb.ondigitalocean.app/eureka}
zuul:
  sensitiveHeaders:
  routes:
    user-serv:
      path: /authserv/**
      service-id: user-service
    wallet-serv:
      path: /walletserv/**
      service-id: wallet-service
    product-serv:
      path: /productserv/**
      service-id: product-service
        

---
spring:
    profiles: prod
eureka:
    client:
       serviceUrl:
           defaultZone: ${EUREKA_URI:https://payee-dicovery-server-po7pb.ondigitalocean.app/eureka}
zuul:
  ignoredServices: 'zuul-gateway'
  sensitiveHeaders:
  routes:
    user-serv:
      path: /authserv/**
      url: https://payee-user-service-52hrr.ondigitalocean.app
    wallet-serv:
      path: /walletserv/**
      url: https://payee-wallet-service-ovb4z.ondigitalocean.app
    product-serv:
      path: /productserv/**
      url: https://payee-product-service-yp833.ondigitalocean.app